trigger: none  # Manual run only

pr: none       # Prevent pull request triggers

variables:
  TF_VERSION: '1.5.7'  # Change if you use a different version
  TF_WORKING_DIR: '.'  # Update to match your Terraform working directory


  ARM_CLIENT_ID: $(clientId)
  ARM_CLIENT_SECRET: $(clientSecret)
  ARM_SUBSCRIPTION_ID: $(subscriptionId)
  ARM_TENANT_ID: $(tenantId)         # Use a valid Terraform version

  # Backend variables for Terraform state
  RESOURCE_GROUP_NAME: $(resourceGroupName)
  BACKEND_STORAGE_ACCOUNT: $(backendStorageAccount)
  BACKEND_CONTAINER_NAME: $(backendContainerName)
  BACKEND_KEY: $(backendKey)

stages:
- stage: TerraformDestroy
  displayName: Destroy Infrastructure
  jobs:
  - job: DestroyInfra
    displayName: Terraform Destroy
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - checkout: self

      - script: |
          echo "Installing Terraform ${TF_VERSION}..."
          curl -sL https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -o terraform.zip
          unzip terraform.zip
          sudo mv terraform /usr/local/bin/
          terraform -version
        displayName: 'Install Terraform'

      - script: |
          terraform init -input=false \
            -backend-config="resource_group_name=$(backendResourceGroupName)" \
            -backend-config="storage_account_name=$(backendStorageAccountName)" \
            -backend-config="container_name=$(backendContainerName)" \
            -backend-config="key=$(backendKey)"
        workingDirectory: $(TF_WORKING_DIR)
        displayName: 'Terraform Init'
        env:
          ARM_SUBSCRIPTION_ID: $(subscriptionId)
          ARM_CLIENT_ID: $(clientId)
          ARM_CLIENT_SECRET: $(clientSecret)
          ARM_TENANT_ID: $(tenantId)

      - script: terraform destroy -auto-approve
        workingDirectory: $(TF_WORKING_DIR)
        displayName: 'Terraform Destroy'
        env:
          ARM_SUBSCRIPTION_ID: $(subscriptionId)
          ARM_CLIENT_ID: $(clientId)
          ARM_CLIENT_SECRET: $(clientSecret)
          ARM_TENANT_ID: $(tenantId)
